WHITESPACE = _{ " " | "\t" | "\n" | "\r" }
COMMENT = _{ ";" ~ (!"\n" ~ ANY)* }

file = { SOI ~ sexpr* ~ EOI }

sexpr = { typed | atom | list }

typed = { (atom | list) ~ ":" ~ type_name }

type_name = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_" | "-")* }

atom = { symbol | number }

symbol = @{ (ASCII_ALPHA | "_" | "?" | "=" | "<" | ">" | "+" | "-" | "*" | "/" | "!" | "$") ~ (ASCII_ALPHANUMERIC | "_" | "-" | "+" | "*" | "/" | "=" | "<" | ">" | "?" | "!" | "." | "$")* }

number = @{ "-"? ~ ASCII_DIGIT+ }

list = { "(" ~ sexpr* ~ ")" }
